---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: c60c980e561ed3e73101667fe8365c609d19a438  # frozen: v0.15.9
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^doc/guides/_examples/
      - id: ruff-format
        exclude: ^doc/guides/_examples/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        exclude: "\\.svg$|\\.map$|\\.min\\.css$|\\.min\\.js$|\\.po$|\\.pot$"
      - id: end-of-file-fixer
        exclude: "\\.svg$|\\.map$|\\.min\\.css$|\\.min\\.js$|\\.po$|\\.pot$"
      - id: check-toml
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: a1785f8e81fe9936d828bef574e6db07e8c8c374  # frozen: 0.12.23
    hooks:
      - id: uv-lock
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run --all-extras mypy
        language: system
        types_or: [python, pyi]
        pass_filenames: false
        require_serial: true
  - repo: https://github.com/codespell-project/codespell
    rev: 2ccb47ff45ad361a21071a7eedda4c37e6ae8c5a  # frozen: v2.4.2
    hooks:
    - id: codespell
      args: [--write-changes]
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: fa412071e4f5d44d44f9e365f4676f9df92456a2  # frozen: v1.30.1
    hooks:
      - id: zizmor
