[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[project]
name = "scim2-sqlalchemy"
version = "0.0.0"
description = "Painless SCIM integration for SQLAlchemy"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE"]
keywords = ["scim", "scim2", "provisioning", "sqlalchemy", "rfc7643", "rfc7644"]
authors = [
    { name = "Éloi Rivard", email = "eloi@yaal.coop" }
]
requires-python = ">=3.11"
dependencies = [
    "scim2-models>=0.12.0",
    "scim2-server>=0.7.0",
    "sqlalchemy>=2.0.41",
]

[project.optional-dependencies]
asyncio = [
    "sqlalchemy[asyncio]>=2.0.41",
]

[project.urls]
documentation = "https://scim2-sqlalchemy.readthedocs.io"
repository = "https://github.com/python-scim/scim2-sqlalchemy"
funding = "https://github.com/sponsors/python-scim"

[dependency-groups]
dev = [
    "aiosqlite>=0.22.1",
    "sqlalchemy[asyncio]>=2.0.41",
    "mypy>=2.3.1",
    "prek>=0.1.0",
    "psycopg[binary]>=3.3.6",
    "pytest>=8.2.1",
    "pytest-cov>=7.1.0",
    "pytest-postgresql>=9.1.0",
    "scim2-client>=0.12.0",
    "scim2-server[testing]>=0.7.0",
    "scim2-tester>=0.5.2",
    "tox-uv>=1.36.0",
    "werkzeug>=3.1.8",
]
doc = [
    "shibuya>=2024.5.15",
    "sphinx>=7.3.7",
    "sphinx-design>=0.7.0",
    "sphinx-issues>=5.0.0",
]

[tool.ruff.lint]
select = [
    "B", # flake8-bugbear
    "D", # pydocstyle
    "E", # pycodestyle
    "F", # pyflakes
    "I", # isort
    "UP", # pyupgrade
]
ignore = [
    "E501", # line-too-long
    "E722", # bare-except
    "D100", # public module
    "D101", # public class
    "D102", # public method
    "D103", # public function
    "D104", # public package
    "D105", # magic method
    "D106", # nested class
    "D107", # public init
    "D203", # no-blank-line-before-class
    "D213", # multi-line-summary-second-line
]

[tool.ruff.lint.isort]
force-single-line = true

[tool.ruff.format]
docstring-code-format = true

[tool.coverage.run]
source = ["scim2_sqlalchemy", "tests"]
branch = true

[tool.mypy]
plugins = ["pydantic.mypy"]
files = ["src/scim2_sqlalchemy"]
strict = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true

[tool.pytest.ini_options]
testpaths = ["tests", "doc"]
addopts = "--doctest-modules --doctest-glob='*.rst' --ignore=doc/conf.py"
pythonpath = ["doc/_examples"]
doctest_optionflags = "ALLOW_UNICODE ELLIPSIS NORMALIZE_WHITESPACE"

[tool.uv]
exclude-newer = "14 days"
exclude-newer-package = { scim2-models = false, scim2-client = false, scim2-server = false, scim2-cli = false, scim2-tester = false, pytest-scim2-server = false }

[tool.tox]
requires = ["tox>=4.19"]
env_list = [
    "style",
    "py311",
    "py312",
    "py313",
    "py314",
    "minversions",
    "doc",
    "coverage",
]

[tool.tox.env_run_base]
runner = "uv-venv-lock-runner"
dependency_groups = ["dev"]
commands = [
    ["pytest", "--showlocals", "--full-trace", "{posargs}"],
]

[tool.tox.env.style]
runner = "uv-venv-runner"
commands = [
    ["prek", "run", "--all-files", "--show-diff-on-failure"],
]

[tool.tox.env.minversions]
runner = "uv-venv-runner"
uv_resolution = "lowest-direct"
package = "editable"

[tool.tox.env.doc]
dependency_groups = ["doc"]
commands = [
    ["sphinx-build", "-W", "--keep-going", "--builder", "html", "doc", "build/sphinx/html"],
]

[tool.tox.env.coverage]
commands = [
    ["pytest", "--cov", "--cov-fail-under=100", "--cov-report", "term:skip-covered", "{posargs}"],
    ["coverage", "html"],
]
